version: '3.7'

services:
  db:
    image: 'postgres:16'
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5444:5432'
    environment:
      POSTGRES_USER: puzzled
      POSTGRES_DB: puzzled
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  dbdata:
